### ISSUE TITLE
error while comment

### ISSUE THREAD

**Issue by jonakaxom** [pythontester192/IG-Bot#5]
Can't create base directory: C:\Program Files\Google\GoogleUpdater

Next when i type comment it shows 

Type your comment: nice
Traceback (most recent call last):
  File "like_cmt_follow.py", line 84, in <module>
    main()
  File "like_cmt_follow.py", line 47, in main
    like_post = browser.find_element_by_xpath("//section[@class= '_aamu _aat0']/span[1]/button")
  File "C:\Users\himangshu\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\himangshu\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\himangshu\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\himangshu\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//section[@class= '_aamu _aat0']/span[1]/button"}
  (Session info: chrome=108.0.5359.99)

C:\Users\himangshu\Downloads\IG-Bot-main\IG-Bot-main>[8820:3964:1213/155503.412:ERROR:gpu_init.cc(523)] Passthrough is not supported, GL is disabled, ANGLE is

**Comment by jonakaxom** [comment]
# Like a post 
        like_post = browser.find_element_by_xpath("//section[@class= '_aamu _aat0']/span[1]/button")
        like_post.click()
        print("Liked!")
        sleep_for_period_of_time() 


 this script is not working
